backup database [HZN_CITRUS]
TO DISK = N'C:\temp\ag\backup\HZN_CITRUS_20180621.bak'
WITH INIT,COMPRESSION,STATS=10


RESTORE FILELISTONLY
FROM DISK = N'C:\temp\ag\backup\HZN_CITRUS_20180621.bak'

--RESTORE DATABASE [HZN_CITRUS]
--FROM DISK = N'C:\Temp\AG\Backup\HZN_QUALITY_FULL_20171101010051.bak'
--WITH FILE = 1,
--MOVE N'Horizon' TO N'C:\Temp\AG\AG_SQL\Data\HZN_QUALITY_Data.mdf',
--MOVE N'Horizon_log' TO N'C:\Temp\AG\AG_SQL\Log\HZN_QUALITY_Log.ldf',
--NORECOVERY,REPLACE,STATS=10

RESTORE DATABASE [HZN_CITRUS_Repl]
FROM DISK = N'C:\temp\ag\backup\HZN_CITRUS_20180621.bak'
WITH FILE = 1,
MOVE N'Horizon' TO N'D:\Data\HZN_CITRUS_Repl_Data.mdf',
MOVE N'Horizon_log' TO N'D:\Log\HZN_CITRUS_Repl_Log.ldf',
RECOVERY,REPLACE,STATS=10

